### ISSUE TITLE
Reset Wizard?

### ISSUE THREAD

**Issue by jeffhoang** [VinceG/twitter-bootstrap-wizard#106]
How do I reset the wizard upon submission?

**Comment by shamanis** [comment]
I join issue. I have to call location.reload() in onFinish. Lost all asynchronous. Trigger 'click' for 'a[href=tab]' does not make sense because onTabClick disable in my case.

**Comment by kheide** [comment]
Cant get your solution to work either @shamanis !

Has anyone else figured out something? Author?

**Comment by jeffhoang** [comment]
I'm using reactjs with this.  My work around was to store the original dom and its children in an instance variable. Upon submission or cancellation, I just restore (replace) the modified selector with the original dom.

**Comment by VinceG** [comment]
@jeffhoang @kheide @shamanis  there is a method called resetWizard
