### ISSUE TITLE
Navigating over hidden steps?

### ISSUE THREAD

**Issue by davidkeaveny** [VinceG/twitter-bootstrap-wizard#110]
I am implementing a wizard process that needs to hide one or more tabs based on selections made by the user in earlier tabs. However, when a tab is hidden, the navigation does not move to the next visible tab (for instance, on the http://vadimg.com/twitter-bootstrap-wizard-example/examples/remove-step.html sample page, hide the tab "Fourth" by entering 3 in the textbox and clicking Hide, then use the Next button to navigate forwards - when you reach the hidden tab, the content is still rendered although the tab is hidden.

Is there a way of implementing such branching logic, especially where different tabs will be displayed based on earlier choices?

**Comment by lordelph** [comment]
@davidkeaveny - did you resolve this? I'm having a similar problem. For example, if I set up a wizard and then hide one of the tabs like this:
~~~~~~~~.js
$('#mywiz').bootstrapWizard('hide', 2);
$('#mywiz').bootstrapWizard('resetWizard');
~~~~~~~~
the tab does not get skipped when next is pressed

**Comment by lordelph** [comment]
What what it's worth, I altered nextIndex and previousIndex to look for a tab which is visible:
~~~~~~~~js
    this.nextIndex = function() {
        var idx;

        for (idx=$navigation.find(baseItemSelector).index($activeTab)+1;
             idx <= obj.navigationLength();
             idx++) {

            if ($navigation.find(baseItemSelector + ':eq(' + idx + ') a').is(":visible")) {
                break;
            }
        }
        return idx;
	};
	this.previousIndex = function() {

        var idx;

        for (idx=$navigation.find(baseItemSelector).index($activeTab)-1;
             idx >= 0;
             idx--) {

            if ($navigation.find(baseItemSelector + ':eq(' + idx + ') a').is(":visible")) {
                break;
            }
        }
        return idx;
	};

~~~~~~~~

**Comment by VinceG** [comment]
@lordelph that's great. let me know if you have the time to create a pull request.
