### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by Jericho** [VinceG/twitter-bootstrap-wizard#113]
Has anybody used a captcha with the bootstrap wizard? 

What I'm trying to accomplish is:
- make sure the "submit" button is disabled
- display a captcha on the last tab
- enable the submit button when the captcha is successfully completed (the captcha jQuery control I am using raises an event when successfully completed)

**Comment by VinceG** [comment]
@Jericho simply $('...').attr('disabled', true);
