### ISSUE TITLE
Force specific tab

### ISSUE THREAD

**Issue by neotropic2023** [VinceG/twitter-bootstrap-wizard#115]
Hey there, great plugin. Something I noticed and acting weird.

I have a form inside the wizard. People selecting options for a purchase (advertising). The last step and since I can not place a form within a form (obviously), I make the actual form you enter the details for CC on a dialog. My own reasoning why two forms. Storing data first before purchase in case something happens and all the info they entered is still there, saved.

What I am trying to achieve. On step 4 (index 4) it is just a simple loading icon ect.. and opens a dialog. When the dialog opens, and say something happens, they change their mind on something they hit cancel, dialog closes, goes back to step 3. 

First time, works great. Second time. Goes back two steps. Third time goes back three steps. Kind of confusing when they have to click to get to the end to step four and the last index is 3. When they click to close the dialog, I run this '$(".previous a").click();'. Any way to tell it to just go to index 3? It is like it ignores storing anything after I click next upon closing the dialog. Yet moves forward when clicked. And the last index is always 3. How does it go back 2 or 3 steps once at the end on the 2nd and 3rd time? 

Thanks.

**Comment by VinceG** [comment]
@neotropic2023 can you try

$('#rootwizard').bootstrapWizard('show',3);

??

**Comment by neotropic2023** [comment]
Thanks! Will give it a shot. Project on hold at the moment.

**Comment by neotropic2023** [comment]
Awesome, it works great.
$('#rootwizard').bootstrapWizard('show',2); is what I needed. 0,1,2,3

**Comment by karaspr** [comment]
> Awesome, it works great.
> $('#rootwizard').bootstrapWizard('show',2); is what I needed. 0,1,2,3

Where exactly did you put this code? Somewhere in \<a\> section? I think I'm looking  for the same thing as you
