### ISSUE TITLE
Wizard buttons not working

### ISSUE THREAD

**Issue by almogdesign** [VinceG/twitter-bootstrap-wizard#116]
Trying to create the next and pervious buttons but it's not working their always disabled. Using the following example - http://vadimg.com/twitter-bootstrap-wizard-example/examples/basic-custombuttons.html

My code:
```javascript
 $('#w4').bootstrapWizard({'nextSelector': '.button-next', 'previousSelector': '.button-previous'});
```

```html
<input type='button' class='btn button-next' name='next' value='Next' data-toggle="tab" />
<input type='button' class='btn button-previous' name='previous' value='Previous' />
```

what I'm getting as you can see their always disabled 

![screen shot 2015-01-07 at 4 48 24 am](https://cloud.githubusercontent.com/assets/169507/5640025/aa6d2a14-9628-11e4-8ee0-bc95e989d846.png)

**Comment by VinceG** [comment]
@almogdesign not sure if this is a plugin issue. can you provide a live example?

**Comment by almogdesign** [comment]
@VinceG I tried a different wizard thanks
