### ISSUE TITLE
Doesn't work in Wordpress

### ISSUE THREAD

**Issue by sanmen1593** [VinceG/twitter-bootstrap-wizard#118]
I'm using it in Wordpress. I'm already use bootstrap in my wordpress template. I just add de bootstrap wizard file and the example that we can find in http://vadimg.com/twitter-bootstrap-wizard-example/examples/basic-progressbar.html

In my footer, just before the "body" end tag, i put the code: http://pastebin.com/ihuLLEYG
```javascript
<script>
        jQuery(document).ready(function() {
                jQuery('#rootwizard').bootstrapWizard({onTabShow: function(tab, navigation, index) {
                        var $total = navigation.find('li').length;
                        var $current = index+1;
                        var $percent = ($current/$total) * 100;
                        jQuery('#rootwizard').find('.progress-bar').css({width:$percent+'%'});
                }});   
        });    
</script>
```
But it doesn't work. Is there a known bug with this on Wordpress?

**Comment by VinceG** [comment]
@sanmen1593 any errors in console?

**Comment by sanmen1593** [comment]
@VinceG Nope. Just doesn't work the effects. I'm not using bootstrap wizard any more, i develop my own "script" that aproach a little with de wizard.
Thanks anyway.

A clue can be the version of bootstrap and jQuery, but didn't have time to check.

**Comment by samjco** [comment]
Yes, I'm using with WordPress. It is the version conflict I bet.
