### ISSUE TITLE
did you test it on mobile?

### ISSUE THREAD

**Issue by AndrewEastwood** [VinceG/twitter-bootstrap-wizard#119]

**Comment by VinceG** [comment]
@AndrewEastwood  no.

**Comment by stefann42** [comment]
We've been using it on https://freebusy.io/connect with desktop and mobile browsers and it works fine primarily because it doesn't introduce any HTML outside of what Bootstrap already supports and handles when rendering on mobile devices.

**Comment by AndrewEastwood** [comment]
ok
