### ISSUE TITLE
Step Validation using onNext event. 

### ISSUE THREAD

**Issue by scottyc** [VinceG/twitter-bootstrap-wizard#12]
I am using the jquery.validation from the base MVC 4 project in Visual Studio 2012. 
I needed a way to validate only the fields in the current step. 
I looked at the example of the form validation, but it seemed to be leading toward a nightmare of hard coded items that couldn't be reused and difficult to maintain. 

I thought I would share my first implementation of the step validation using the onNext event. My step containers are <div class="tab-pane"> 
It seems that the tab object in the function is a reference to the actual navigation tab and not the step container. 

If you see room for improvements, please let me know as I am not a js ninja :) 

{

 onNext: function (tab, navigation, index) {

```
                    var isValid = false;
                    var hadError = false;
                    var tabs = $(".tab-pane");
                    var currentTab = tabs[index - 1]; 
                    var inputs = $(":input");
                    var stepElements = $(currentTab).find(inputs);
                    var count = stepElements.length;
                    if (count <= 0) {
                        return true;
                    }
                    $(stepElements).each(function (idx) {
                        isValid = $(document.forms[0]).validate().element($(this));
                        if (!isValid) { hadError = true; }
                    });

                    return !hadError;

            },
```

}

**Comment by narangrishab** [comment]
@scottyc Your solution seems to work only for the first tab but it fails on the subsequent tabs. 


 onNext: function (tab, navigation, index) {

					            var isValid = false;	
					            var hadError = false;
					            var tabs = $(".tab-pane");
					            var currentTab = tabs[index - 1];
					            var inputs = $(":input, select");
					            var stepElements = $(currentTab).find(inputs);
					            console.log(stepElements);
					            var count = stepElements.length;
					            if (count <= 0) {
					                return true;
					            }
					            $(stepElements).each(function (idx) {
					                isValid = $(document.forms[0]).validate().element($(this));
					                if (!isValid) { hadError = true; }
					            });

					            if (hadError == false) {

					                if (index == navigation.find('li').length) {
					                    $("form").submit();
					                }

					            }

					            return !hadError;
					    },


$('#createEventForm').validate({
	
           ignore: ":hidden",
           rules: {
				
				eventName : {
					required: true,
					minlength: 3
				},
				startDate:
				{
					required: true
				},
				endDate:
				{
					required: true
				},
				startTime:
				{
					required: true
				},
				endTime:
				{
					required: true
				},
				category:
				{
					required: true,
					min:1
				},
				addressMap:
				{
					required: true
				},
				address:
				{
					required: true
				},
				city:
				{
					required: true
				},
				state:
				{
					required: true
				},
				country:
				{
					required: true
				},
				phoneNumber:
				{
					required: true
				}

           },

           messages:
           {
           		category: { min: "Select a valid category" }
           },
			

           submitHandler: function (form) {

				url = $("#createEventForm").attr("action");
				console.log($("#createEventForm").serialize());
				var data = new FormData(document.forms.namedItem("createEventForm"));

				$(".btn").attr("disabled", true);

				$.ajax({
					type: 'POST',
					url: url,
				    data: data,
				    contentType: false,
	                processData: false,
					success : function(data){
						
						$(".btn").attr("disabled", false);

						data = $.parseJSON(data);	
						
						if(data.code == 200)
						{
							$("#errors").text(''); 
							$("#errors").show();
							$("#errors").append(data.message);
						}
						else
						{
							$("#errors").text(''); //TO NULLIFY PREVIOUS ERRORS
							$.each(data.message,function(key1,value1)
							{		
								$.each(value1, function(key2, value2){
								$("#errors").append(value2+"<br>");	
								$("#errors").show();	
								});
							});
								
						}

					}	
				})
           }
       });

**Comment by andrew-za** [comment]
With jQuery you can loop through all visible elements and check their values. I have a function which I run in the "onNext" option:

`function checkinputs() {
        var unfilled = 0;
        $('input,textarea,select').filter('[checkme]:visible').each(function(){
            unfilled = 0;
            if (($(this).is(':radio') || $(this).is(':checkbox'))
                    && !$('input[name="'+$(this).attr('name')+'"]:checked').val()) {
                alert('Please checkbox');
                unfilled = 1;
            } else if(!$(this).val()) {
                alert('Please fill in');
                unfilled = 1;
            }
        });
        return unfilled;
    }`

**Comment by Ocoolsanni** [comment]
Hey  @scottyc  and @neara hope you got what you were looking for today I had the same issue but this link saved me a lot http://formvalidation.io/examples/bootstrap-wizard/ someone can try this hope it helps
