### ISSUE TITLE
Left Nav layout doesnt work anymore

### ISSUE THREAD

**Issue by craiglondon** [VinceG/twitter-bootstrap-wizard#120]
When the CSS from Bootstrap went from 2.3.x to 3.x left nav doesn't work anymore.

![capture](https://cloud.githubusercontent.com/assets/3833140/6470739/c622fe3a-c1b3-11e4-8a83-caccf1a1a611.JPG)

**Comment by VinceG** [comment]
@craiglondon you mean the previous button?

**Comment by craiglondon** [comment]
I was expecting the tabs to be vertical not horizontal, like it is on this page.

http://vadimg.com/twitter-bootstrap-wizard-example/examples/basic-tabsleft.html

**Comment by VinceG** [comment]
@craiglondon guess it was removed in 3.x
http://stackoverflow.com/questions/18432577/stacked-tabs-in-bootstrap-3
