### ISSUE TITLE
bootstrap-wizard inside bootstrap-modal

### ISSUE THREAD

**Issue by rajagcha** [VinceG/twitter-bootstrap-wizard#13]
Hello,

This is not an issue, it could be classified as a question or an enhancement. I am planning on using this wizard and attaching the same inside the body class of bootstrap modal. Would like to know if its common to have a bootstrap wizard inside a modal for create operation (Create/Edit). If so has anyone come across any issues or potential recommendations to start with. Would like to know before i give it a try on possible issues or better alternatives to achieve the same.

**Comment by Aeoline** [comment]
I'll happily wished to know how it works as i'm trying to make it work in a modal, and it doesn't seem to reply. Changed a little like biskit adviced, don't seem to work. 

Any clue ?

**Comment by Howardno** [comment]
Worked on this issue for far too long now.
The sollution for me was to load the wizard code after the modal has opened .
`$( "#modal" ).on('shown', function(){
 FormWizard.init();
});`

FormWizard.init(); contains all wizard code.
Hopefully this helps somebody

**Comment by Doopin** [comment]
Instead the following event worked for me `shown.bs.modal`  this way 

> $("#modal").modal('show').on('shown.bs.modal', function () {
                            FormWizard.init();
                    });
