### ISSUE TITLE
Finish button not supported when using minified version of lib.

### ISSUE THREAD

**Issue by michalborek** [VinceG/twitter-bootstrap-wizard#145]
When I use min.js of your lib, the "finishSelector" attribute does not work. Generally the whole "finish" related functionality seems to be missing.

**Comment by michalborek** [comment]
Closing, since pull request is created

**Comment by VinceG** [comment]
@michalborek how did you install it? using bower?
the minified version does have the finish functionality in it, the one in master. the tags most likely don't have it. can you verify the version you are using.

thank you.

**Comment by pwoo** [comment]
Just chiming in as I faced the same problem -- Michael is correct; there are no references to the word "finish" in the minified, master copy of the file at all.

**Comment by VinceG** [comment]
thank you. pull request merged.
