### ISSUE TITLE
On Hiding Step, Previous button not works

### ISSUE THREAD

**Issue by naveedyousaf09** [VinceG/twitter-bootstrap-wizard#158]
Hi, 
This plugin is great,

I found an issue in this plugin, by fixing bugs this plugin would be more useful

When we hide any tab programmatically, then surprisingly 'Previous' button stops working, 

This issue also persists in the given examples

Regards,
Naveed Yousaf

**Comment by ishouvik** [comment]
Thank you very much, Naveed. I will push this to the Rails gem as well. https://rubygems.org/gems/twitter_bootstrap_wizard_rails

~ Cheers!

**Comment by VinceG** [comment]
@naveedyousaf09 you need to call refresh.
