### ISSUE TITLE
next/previous button error on click

### ISSUE THREAD

**Issue by pepperav** [VinceG/twitter-bootstrap-wizard#160]
Hi,
simply copy _basic.html_ example I get this error on click to 'next' button or 'previous' button:

	Uncaught Error: Syntax error, unrecognized expression: li:has([data-toggle="tab"])::visible:eq(1) 
		aSizzle.error @ jquery-latest.js:1473
		Sizzle.tokenize @ jquery-latest.js:2087
		Sizzle @ jquery-latest.js:845
		jQuery.fn.extend.find @ jquery-latest.js:2704
		previous @ jquery.bootstrap.wizard.js:98
		jQuery.event.dispatch @ jquery-latest.js:4641
		elemData.handle @ jquery-latest.js:4309

Using _bootstrap 3.3.4_ and _jquery-1.11.2.js_

Thank you

**Comment by VinceG** [comment]
@pepperav can you try with latest on master?

thank you.

**Comment by pepperav** [comment]
On master? I've tried using jQuery-11 and 12 too.
Il 14 gen 2016 17:52, "Vincent Gabriel" <notifications@github.com> ha
scritto:

**Comment by VinceG** [comment]
@pepperav sorry, i meant i fixed it earlier. can you try again.

**Comment by VinceG** [comment]
just tested myself again all examples work. thank you.

**Comment by pepperav** [comment]
ok it works!
great job really thank you
