### ISSUE TITLE
withVisible: false

### ISSUE THREAD

**Issue by StevenNell** [VinceG/twitter-bootstrap-wizard#162]
Hi guys,

please check this bug out:

$navigation.find(baseItemSelector + ':' + ($settings.withVisible ? 'visible' : '') + ':eq(' + $index + ') a').tab('show');

if $settings.withVisible is false it produces a bad selector:
li:has([data-toggle="tab"])::eq(1)
(the double colon) 

the above needs to change to 
$navigation.find(baseItemSelector + ($settings.withVisible ? ':visible' : '') + ':eq(' + $index + ') a').tab('show');

**Comment by VinceG** [comment]
This was fixed yesterday. Can you check with master or tag 1.3.1

Please excuse my brevity, sent from my iPhone

**Comment by StevenNell** [comment]
Hi Vince – the name is Steven.

 

Pleased to meet you – thank you for the quick response and don’t worry about the brevity – it is understood.

 

Please see below:



Check the highlighted below fro master.

 



 

 

 

Kind Regards,

 

Steven Nell

Mobile: 072 408 2503

Email:  <mailto:steven@nocoffeebreaks.com> steven@nocoffeebreaks.com

**Comment by VinceG** [comment]
@StevenNell fixed in 1.3.2
