### ISSUE TITLE
Next/previous button in pagers step into disabled tabs

### ISSUE THREAD

**Issue by jstaerk** [VinceG/twitter-bootstrap-wizard#163]
In version 1.3.2: After having disabled a tab using $('#rootwizard').bootstrapWizard('disable', 2);, the button "next" in the page before the disabled page will not step into the next page which is not disabled, but into the disabled page (where neither next nor previous can be used). If I change to a page after the disabled page, the "previous" button will also jump into the disabled page. I would have had expected that "next" jumps to the next, not-disabled page.

**Comment by VinceG** [comment]
That's a know issue we need a selector for the next and previous even to match non disabled tabs. Just like we have with the visible selector and the withVisible property. 

Would you like to create a PR?

Please excuse my brevity, sent from my iPhone

**Comment by jstaerk** [comment]
I excuse your brevity, just it just took me a minute to realize that you mean pull request, not press release :-) I'll have a look into it but I'm short in time and not yet experienced with your code, so please don't count on me solving it right away. If a proper solution takes me too long I might also go for a workaround. But I will have a look at it and thanks for the otherwise great widget.
