### ISSUE TITLE
composer Packagist

### ISSUE THREAD

**Issue by myDelevop** [VinceG/twitter-bootstrap-wizard#165]
Hello guys,
sorry for my bad English, 
I would like to ask you how I can insert twitter-bootstrap-wizard's dependency in my project using composer?

**Comment by VinceG** [comment]
you can use npm not composer.

**Comment by karllhughes** [comment]
@VinceG I can't seem to find the latest updates to this package on NPM. I just see [this old version](https://www.npmjs.com/package/twitter-bootstrap-wizard).

Do you have any plans to release v.1.3.2 on NPM?
