### ISSUE TITLE
.container class now breaks responsivness

### ISSUE THREAD

**Issue by losttheplot** [VinceG/twitter-bootstrap-wizard#166]
The Bootstrap .container class is now primarily intended to wrap a site's contents ( http://getbootstrap.com/css/#overview-container ) and therefore sets a fixed width relative to the viewport. It used to be the case that Bootstrap allowed containers inside navbars by setting: .navbar .container { width: auto } but that no longer seems to be the case (.3.3.6).

By using the .container class within twitter-bootstrap-wizard's navbar, the pills no longer wrap to the wizard container's width when not being used at full page width.

Unless I'm missing something (possible), either the use of the .container class needs to change, or an additional css style needs to set its width to auto.

**Comment by VinceG** [comment]
@losttheplot it's up to you to decide the markup for the navigation bar. the demo just shows how this can be done as an example, since that was created for bootstrap 2 and then early 3.x version it might not be the best option any longer. feel free to change the markup.
