### ISSUE TITLE
shows disabled tabs after click, onTabChange return value ignored

### ISSUE THREAD

**Issue by jstaerk** [VinceG/twitter-bootstrap-wizard#167]
when hovering over disabled tabs, the mouse pointer changes as if it were inactive, but in fact, if one clicks on a disabled tab, the content will still be shown to the user. 

Another aspect of the same problem: false return values of onTabChange are ignored.

**Comment by Paul-Luo** [comment]
I have encountered the same problem, and I changed 'shown' to 'show', and bind 'onTabChange' and 'onTabClick' event.
