### ISSUE TITLE
example url error

### ISSUE THREAD

**Issue by alsotang** [VinceG/twitter-bootstrap-wizard#173]
http://vadimg.com/twitter-bootstrap-wizard-example/examples/basic-disabletabshow.html

is the same as 

http://vadimg.com/twitter-bootstrap-wizard-example/examples/basic-disabletabclick.html

**Comment by VinceG** [comment]
@alsotang thank you. i've updated the example site

http://vinceg.github.io/twitter-bootstrap-wizard/
