### ISSUE TITLE
Conflict with jquery 3.0.0

### ISSUE THREAD

**Issue by Baldrani** [VinceG/twitter-bootstrap-wizard#187]
jQuery.Deferred exception: $(...).bootstrapWizard is not a function TypeError: $(...).bootstrapWizard is not a function
    at HTMLDocument.<anonymous> (http://agencedevoyage.app:8000/alacarte:648:22)
    at j (http://agencedevoyage.app:8000/js/base.js:2:29588)
    at k (http://agencedevoyage.app:8000/js/base.js:2:29902) undefined

**Comment by NoMan2000** [comment]
This is not a good way to write an error report. You have no code that shows what you did or did not do wrong, include the original code.

First, try to use the Jquery Migrate plugin.  If that fixes the problem, then there might be an issue. 

However, the error you are getting is a completely different error.  It looks like you haven't even included the code for this plugin at all, hence, bootstrapwizard is not a function.
