### ISSUE TITLE
 suggestion：After merge or realease  ,not only  update description version of  README.md  also update  description version of  jquery.bootstrap.wizard.js（jquery.bootstrap.wizard.min.js）

### ISSUE THREAD

**Issue by chnpassion** [VinceG/twitter-bootstrap-wizard#211]
suggestion：After merge or realease  ,not only  update  **description version of  README.md**  also update  **description version of  jquery.bootstrap.wizard.js**（_jquery.bootstrap.wizard.min.js_）,avoid Version error description afer download!
![image](https://cloud.githubusercontent.com/assets/25994039/23992647/ad46dbe2-0a78-11e7-9379-62ce1693d358.png)

**Comment by VinceG** [comment]
fixed
