### ISSUE TITLE
Bootstrap 4 Integreation

### ISSUE THREAD

**Issue by dydaniely** [VinceG/twitter-bootstrap-wizard#219]

**Comment by dydaniely** [comment]
Is it integrated with bootstrap 4

**Comment by VinceG** [comment]
No

-----
Vincent Gabriel
Software Engineer

Please excuse my brevity, sent from my iPhone

**Comment by PythooonUser** [comment]
Hey @VinceG. Is a Bootstrap 4 integration planned then? Do you expect breaking changes? Thanks in advance.

**Comment by VinceG** [comment]
@PythooonUser I have no plans on having a Bootstrap 4 version of this. There are other alternatives out there that work with Bootstrap 4 already.

**Comment by brunnopleffken** [comment]
@VinceG To be honest, I tried other alternatives but none of them looks great as yours...
