### ISSUE TITLE
Dynamic Steps

### ISSUE THREAD

**Issue by AbuAlKarmi** [VinceG/twitter-bootstrap-wizard#35]
Could you please add a functionality to add new Dynamic Steps ( tab and content ).

**Comment by a3aakash** [comment]
can anybody tell me how to apply dynamic steps?

**Comment by anorborg** [comment]
@a3aakashI haven't used this in a while, but here is a comment I posted about using dynamic steps with angular a while ago (http://disq.us/p/jcr6jj). The reset I refer too is now in the code and should be doable. I don't have time to put together an example, but basically add the steps to the DOM in javascript and call the resetWizard method. Hope this helps.

**Comment by a3aakash** [comment]
@anorborg I have use the same steps you have mentioned but using resetWizard function it all away clears up the form inside the tab content. So I am pretty much confused that is dynamic steps are possible in middle or not. I have also created an issue regarding this #203 . Please @VinceG look into this matter as it is very urgent. Thank you.

**Comment by a3aakash** [comment]
@anorborg i found the solution of getting dynamic steps in middle as in reset wizard you are calling fixNavigationButtons which is only used when you want to empty the fields of whole form. If you are adding steps within the form wizard the you dont want that function to be called. Thank you. have a nice day.. :)
