### ISSUE TITLE
Returning False for onTab(Show|Change|Click) Does Not Cancel

### ISSUE THREAD

**Issue by esheri3** [VinceG/twitter-bootstrap-wizard#39]
Returning false in the onTabShow, onTabChange, and onTabClick events does not prevent the wizard from moving onward to the next section. This was tested using the latest version in Github at the time of writing.

Simple Ex:

$('#container .bootstrap-wizard-component').bootstrapWizard({
     'onTabChange': function(tab, navigation, index) {
          return false; // does not actual cancel tab change
     }
});

**Comment by David-Melo** [comment]
Just in case anybody else runs into this like I did.

Using a combination of  `onTabClick` and `onNext` I was able to prevent navigating based on validation

**Comment by digEmAll** [comment]
@David-Melo : could please create a jsfiddle example ?
You can modify this if you like: http://jsfiddle.net/157ttz1p/1/

**Comment by David-Melo** [comment]
@digEmAll http://jsfiddle.net/157ttz1p/4/

Here you go, basically I wired every tabchange method to a validator function and pass in the current wizard tab. If the validation for that tab hasn't been met, then navigation is prevented. Hope this helps.

**Comment by digEmAll** [comment]
@David-Melo thanks a lot :)

**Comment by siliconalchemy** [comment]
Using the latest code, returning false for onTabClick doesn't work:
onTabClick: function(tab, navigation, index) {
               return false;
}
It doesn't seem possible to disable tab clicks, which is a problem.

**Comment by 4pr3x** [comment]
onTabClick: function(tab, navigation, index) {
return false;
}
Is working for me! 
Only issue I have with onTabClick function is, that my "prev" & "next" button´s CSS is  for some reason changed.

**Comment by gayanc** [comment]
Wizard with disabled tab click not working?

http://vadimg.com/twitter-bootstrap-wizard-example/examples/basic-disabletabshow.html

any clue how to fix this?

**Comment by VinceG** [comment]
@gayanc can you try this:

http://vinceg.github.io/twitter-bootstrap-wizard/examples/basic-disabletabclick.html

**Comment by keremcankaya0** [comment]
After an hour of struggle removing data-toggle=tab from the nav actually worked
