### ISSUE TITLE
Returning false onNext with Ajax not prevent tab to move forward.

### ISSUE THREAD

**Issue by ghost** [VinceG/twitter-bootstrap-wizard#41]
returning false onNext with Ajax not prevent tab to move forward, if my ajax status equal success than move forward otherwise it is stay in currentIndex.

``` javascript
$('#rootwizard').bootstrapWizard('show','currentIndex');
return false;
```

I tried before return false but seems does not effect.    

``` javascript
  $('#rootwizard').bootstrapWizard({
        'tabClass': 'bwizard-steps',
        'onTabClick': function(tab, navigation, index){
          return false;
      },
        'onNext': function(tab, navigation, index) {
      if (index == 1){
        var $valid = $("#d_form").valid();
        if(!$valid) {
          $d_validator.focusInvalid();
          return false;
        }else {
            var $form = $("#d_form");
                form_data = $form.serializeFormJSON() || '';
            $.ajax({
              url : "<?php echo base_url(); ?>joborder/form_wizard1",
              type : 'POST',
              dataType: 'json',
              data : form_data,
              async : false,
              success: function(d){
                if(d.status == 'success'){
                  $.pnotify({
                      title: 'Notification',
                      text: d.message,
                      type: d.status
                    });
                }else {
                  $('#rootwizard').bootstrapWizard('show','currentIndex');
                     return false;
                  // not prevent tab to move forward, 
                }
              }
          });
        }
      }
  });
```

Thanks, sorry for my English.

**Comment by jsonjuri** [comment]
Long time ago, but i was also facing this issue.
Simple solution is manually switch tab in the success function of the ajax call and let the onNext always return false.

var wizard = template.find('#rootwizard')

`var submit_wizard_form = function(form, wizard, tab) {
	var params = form.serialize();
			
	$.ajax({
		type: form.attr('method'),
		url: form.attr('action'),
		data: params,
		success: function(data) {
			if(data.success) {
				wizard.bootstrapWizard('show', tab)	
			}
		},
		error: function(xhr, textStatus, error) {}
	});
};`

`onNext: function(tab, navigation, index) {
						var current = index + 1;
						
						switch (index)
						{
							case 1:
								var valid = form.valid();
								if (!valid) {
									form_validator.focusInvalid();
									return false;
								} else {
									submit_wizard_form(form, wizard, index);										
									return false;
								}
							break;
}
}`
