### ISSUE TITLE
Problem with tag #1.0.0

### ISSUE THREAD

**Issue by brunowego** [VinceG/twitter-bootstrap-wizard#81]
The tag 1.0.0 no have the same files in master branch, for example bower.json.

**Comment by ricardopolo** [comment]
@VinceG you can use a CI like Appveyor or Travis that deploys master to Package Managers automatically

**Comment by VinceG** [comment]
@ricardopolo i don't think so, no.

**Comment by ricardopolo** [comment]
@VinceG why?

**Comment by VinceG** [comment]
@ricardopolo a) i never used it b) i don't have the time to spend on adding it. would you want to help get this done?

**Comment by waza-ari** [comment]
I totally can understand that it can be annoying to support many packet managers. There are however also very good reasons to use packet managing, I don't think I have to mention them here.

Many frameworks (including the three most popular frameworks on the web, being Yii2, Symfony and Laravel) heavily rely on composer and its bower-plugin to handle dependencies. Have a look for example at the following Yii2 plugin (https://github.com/Chofoteddy/yii2-bootstrap-wizard), which uses bower to reference at this very project. It is simply not state of the art to use libraries without dependency management, and it took me nearly 5 hours today to figure out that the "automatically installed dependency" is causing the trouble and that I have to fetch master-code manually.

So all this text written for one purpose: please consider maintaining at least the most popular package managers.

**Comment by VinceG** [comment]
@waza-ari i understand the frustration. i initially planned on supporting bower and i did for a certain period of time, however, i can't keep maintaining  this and other projects i have by myself. will you be interested in helping getting this updated on bower?

**Comment by waza-ari** [comment]
@VinceG Sorry, I did not want to sound frustrated. I haven't worked with bower yet, but have experiences with composer as PHP packet management system. When your time is the problem, I'd be glad to help. Just need to get into it.

**Comment by VinceG** [comment]
i believe composer is for PHP dependencies and bower is used for asset management.

**Comment by waza-ari** [comment]
Yes, I am aware of that. Just wanted to point out that I did not work with bower yet, but that I am not totally new to this topic. Maybe we should get in touch apart from this issue to negotiate how I can support you?

**Comment by VinceG** [comment]
@waza-ari having this on bower will be a great help to start with.
