### ISSUE TITLE
OnTabClick Event should include not only the currentTab, but also the tab you clicked

### ISSUE THREAD

**Issue by JohnBergman** [VinceG/twitter-bootstrap-wizard#92]
while working with the wizard, I discovered that the OnTabClick event does not include any information about what the next page is that you are navigating to.  The other events, NextTab/PreviousTab this information can be inferred.

**Comment by AmitPatel-BoTreeConsulting** [comment]
Can anybody please update if we can get index of clicked tab?

```
onTabClick: function(tab, navigation, index){
  alert(index);
}
```
displays wrong index number. Clicking on same tab again shows correct tab index.
