### ISSUE TITLE
Not compatible with bootstrap version 3.2

### ISSUE THREAD

**Issue by ramanathanMuthuraman** [VinceG/twitter-bootstrap-wizard#99]
The progress bar does not update on user actions. Even though v3.2 is not specified in the requirements, it is a great widget and if made compatible with the current version, it becomes even better

**Comment by VinceG** [comment]
@ramanathanMuthuraman this is a css issue. example might be outdated but you should change your markup to match the bootstrap one. this just provides the JS functionality of a wizard.
